replicaCount: 1

image:
  repository: cypress-editor
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: cypress.k8dev.bjs.i.wish.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
