replicaCount: 1

image:
  repository: harbor.infra.wish-cn.com/wish/cypress/cypress-editor
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: ""
  annotations:
    ## example for ingress annotions.
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: cypress.k8sqa.bjs.i.wish.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: cypress-editor
              port:
                number: 8080
  tls: []

resources: {}

serviceAccount: {}

autoscaling: {}
